import * as p from "../src/lib/importParse.ts";
const eq=(n:string,a:unknown,b:unknown)=>{const ok=JSON.stringify(a)===JSON.stringify(b);console.log(ok?"PASS":"FAIL",n,ok?"":JSON.stringify(a)+" != "+JSON.stringify(b));if(!ok)process.exitCode=1;};
eq("date us",p.parseDateFlexible("03/30/2026"),"2026-03-30");
eq("date iso",p.parseDateFlexible("2026-3-5"),"2026-03-05");
eq("date bad month",p.parseDateFlexible("13/01/2026"),null);
eq("date feb30",p.parseDateFlexible("02/30/2026"),null);
eq("date text",p.parseDateFlexible("bad"),null);
eq("time 9am",p.parseTimeFlexible("9:00 AM"),540);
eq("time noon",p.parseTimeFlexible("12:00 PM"),720);
eq("time midnight",p.parseTimeFlexible("12:30 AM"),30);
eq("time 3pm",p.parseTimeFlexible("3:00 PM"),900);
eq("time 24h",p.parseTimeFlexible("17:00"),1020);
eq("time 9:30",p.parseTimeFlexible("9:30"),570);
eq("time bad 9:5",p.parseTimeFlexible("9:5"),null);
eq("time 13 pm",p.parseTimeFlexible("13:00 PM"),null);
eq("time 25",p.parseTimeFlexible("25:00"),null);
eq("time seconds",p.parseTimeFlexible("9:00:30 am"),540);
eq("role admin pm",p.parseRole("Admin, Project Manager"),{role:"ADMIN",unknown:[]});
eq("role team mgr",p.parseRole("Team Manager"),{role:"LEADER",unknown:[]});
eq("role blank",p.parseRole(""),{role:"MEMBER",unknown:[]});
eq("role our export",p.parseRole("Team/Project Manager"),{role:"LEADER",unknown:[]});
eq("role location",p.parseRole("Location manager"),{role:"LOCATION",unknown:[]});
eq("role member",p.parseRole("Team member"),{role:"MEMBER",unknown:[]});
eq("role unknown",p.parseRole("Wizard, Admin"),{role:"ADMIN",unknown:["Wizard"]});
eq("weekly 8x5",p.weeklyFromCapacity("8","Mon, Tue, Wed, Thu, Fri"),40);
eq("weekly 4x5",p.weeklyFromCapacity("4","Mon, Tue, Wed, Thu, Fri"),20);
eq("weekly none",p.weeklyFromCapacity("",""),undefined);
eq("weekly 7.5 4 days",p.weeklyFromCapacity("7:30","Monday, Tuesday, Wednesday, Thursday"),30);
eq("weekly bad",p.weeklyFromCapacity("lots","Mon"),null);
eq("weekly cap only",p.weeklyFromCapacity("8",""),40);
eq("split",p.splitList("T4, T2; t4 ,, x"),["T4","T2","x"]);
eq("refs",p.projectRefs("New Project:New Client"),[{name:"New Project:New Client"},{name:"New Project",client:"New Client"}]);
eq("pick",p.pick({a:"",b:" x "},"a","b"),"x");
// Added with the hardening pass: names, durations, access words, budgets, header spacing.
eq("clean spaces", p.clean("  Acme \n  Co\t"), "Acme Co");
eq("clean control", p.clean("A\u0000B"), "A B");
eq("dur decimal", p.parseDurationFlexible("1.5"), 90);
eq("dur h:mm", p.parseDurationFlexible("8:00"), 480);
eq("dur h:mm:ss", p.parseDurationFlexible("08:00:00"), 480);
eq("dur h:mm:ss secs", p.parseDurationFlexible("1:30:45"), 91);
eq("dur 1h 30m", p.parseDurationFlexible("1h 30m"), 90);
eq("dur 90m", p.parseDurationFlexible("90m"), 90);
eq("dur 1:75 rejected", p.parseDurationFlexible("1:75"), NaN);
eq("dur words rejected", Number.isNaN(p.parseDurationFlexible("lots")), true);
eq("dur empty rejected", Number.isNaN(p.parseDurationFlexible("")), true);
eq("dur 1e3 rejected", Number.isNaN(p.parseDurationFlexible("1e3")), true);
eq("dur Infinity rejected", Number.isNaN(p.parseDurationFlexible("Infinity")), true);
eq("access blank", p.parseAccess(""), "PUBLIC");
eq("access everyone", p.parseAccess("Everyone"), "PUBLIC");
eq("access restricted", p.parseAccess("Restricted"), "RESTRICTED");
eq("access private", p.parseAccess(" private "), "RESTRICTED");
eq("access typo", p.parseAccess("Restriced"), null);
eq("budget blank", p.parseBudget(""), null);
eq("budget zero", p.parseBudget("0"), null);
eq("budget 120", p.parseBudget("120"), 120);
eq("budget 12.5", p.parseBudget("12.5"), 12.5);
eq("budget Infinity", Number.isNaN(p.parseBudget("Infinity") as number), true);
eq("budget hex", Number.isNaN(p.parseBudget("0x10") as number), true);
eq("budget 1e999", Number.isNaN(p.parseBudget("1e999") as number), true);
eq("budget too big", Number.isNaN(p.parseBudget("100001") as number), true);
// Added with the review fixes: working days read strictly, blank capacity, old joining dates, owner role, list repeats, bounded project readings, odd files.
eq("days list", p.parseWorkingDays("Mon, Tue, Wed, Thu, Fri"), 5);
eq("days range", p.parseWorkingDays("Mon-Fri"), 5);
eq("days range words", p.parseWorkingDays("Monday to Friday"), 5);
eq("days range dash spaces", p.parseWorkingDays("Mon - Thu"), 4);
eq("days wrap range", p.parseWorkingDays("Sat-Mon"), 3);
eq("days spaces", p.parseWorkingDays("Mon Wed Fri"), 3);
eq("days slash", p.parseWorkingDays("Mon/Tue/Wed"), 3);
eq("days full names", p.parseWorkingDays("Monday, Tuesday, Wednesday, Thursday"), 4);
eq("days repeat", p.parseWorkingDays("Mon, mon, MONDAY"), 1);
eq("days one typo refuses all", p.parseWorkingDays("Mon, Tue, Foo"), null);
eq("days blank", p.parseWorkingDays(""), null);
eq("days words", p.parseWorkingDays("weekdays"), null);
eq("weekly mon-fri", p.weeklyFromCapacity("8", "Mon-Fri"), 40);
eq("weekly typo day", p.weeklyFromCapacity("8", "Mon, Tue, Foo"), null);
eq("weekly blank capacity keeps the default", p.weeklyFromCapacity("", "Mon, Tue, Wed, Thu, Fri"), undefined);
eq("weekly h:mm:ss capacity", p.weeklyFromCapacity("8:00:00", "Mon, Tue, Wed, Thu, Fri"), 40);
eq("weekly 24+ refused", p.weeklyFromCapacity("25", "Mon"), null);
eq("weekly problem days", p.weeklyProblem("8", "Mon-Foo").startsWith("Working Days"), true);
eq("weekly problem capacity", p.weeklyProblem("lots", "Mon").startsWith("Daily Work Capacity"), true);
eq("capacity 7.5", p.parseCapacityHours("7.5"), 7.5);
eq("capacity 7:30", p.parseCapacityHours("7:30"), 7.5);
eq("capacity words", Number.isNaN(p.parseCapacityHours("lots")), true);
eq("date 1985 refused by default", p.parseDateFlexible("1985-06-01"), null);
eq("date 1985 with a wider range", p.parseDateFlexible("1985-06-01", 1900, 9999), "1985-06-01");
eq("date 2999 with a wider range", p.parseDateFlexible("2999-01-01", 1900, 9999), "2999-01-01");
eq("role owner", p.parseRole("Owner"), { role: "ADMIN", unknown: [] });
eq("split repeats after tidying", p.splitList("Design  Review, Design Review, Build"), ["Design Review", "Build"]);
eq("refs long entry has no readings", p.projectRefs("a" + ":b".repeat(5000)), []);
eq("refs at most three client readings", p.projectRefs("a:b:c:d:e:f").length, 4);
eq("clean text keeps line breaks", p.cleanText("a\u0000b\nc\td "), "ab\nc\td");
eq("email with NUL refused", p.EMAIL_RE.test("a\u0000@b.co"), false);
eq("email normal", p.EMAIL_RE.test("a.b+c@d-e.co"), true);
import * as c from "../src/lib/csv.ts";
const objs = (t: string, m?: number) => c.csvObjects(t, m);
eq("csv unclosed quote is reported", objs('Name,Email\nA,"oops\nB,b@x.co').error?.includes("line 2"), true);
eq("csv closed quote fine", objs('Name,Email\n"A, B",a@x.co').rows[0].v.name, "A, B");
eq("csv extra cells flagged", objs("Project,Client\nP,C,Design,Build").rows[0].extra, true);
eq("csv empty trailing cells are not extra", objs("Project,Client\nP,C,,").rows[0].extra, false);
eq("csv header spacing", objs("Start   Date,Email\n1,a").keys, ["start date", "email"]);
eq("csv excel file", objs("PK\u0003\u0004rest").error?.includes("Excel"), true);
eq("csv semicolons", objs("Name;Email\nA;a@x.co").error?.includes("semicolons"), true);
eq("csv too many columns", objs(Array.from({ length: 201 }, (_, i) => "c" + i).join(",") + "\na").error?.includes("200"), true);
eq("csv row cap keeps total", [objs("a\n1\n2\n3\n4", 2).rows.length, objs("a\n1\n2\n3\n4", 2).total], [3, 4]);
