import * as p from "../src/lib/importParse.ts";
const eq=(n:string,a:unknown,b:unknown)=>{const ok=JSON.stringify(a)===JSON.stringify(b);console.log(ok?"PASS":"FAIL",n,ok?"":JSON.stringify(a)+" != "+JSON.stringify(b));if(!ok)process.exitCode=1;};
eq("date us",p.parseDateFlexible("03/30/2026"),"2026-03-30");
eq("date iso",p.parseDateFlexible("2026-3-5"),"2026-03-05");
eq("date bad month",p.parseDateFlexible("13/01/2026"),null);
eq("date feb30",p.parseDateFlexible("02/30/2026"),null);
eq("date text",p.parseDateFlexible("bad"),null);
eq("time 9am",p.parseTimeFlexible("9:00 AM"),540);
eq("time noon",p.parseTimeFlexible("12:00 PM"),720);
eq("time midnight",p.parseTimeFlexible("12:30 AM"),30);
eq("time 3pm",p.parseTimeFlexible("3:00 PM"),900);
eq("time 24h",p.parseTimeFlexible("17:00"),1020);
eq("time 9:30",p.parseTimeFlexible("9:30"),570);
eq("time bad 9:5",p.parseTimeFlexible("9:5"),null);
eq("time 13 pm",p.parseTimeFlexible("13:00 PM"),null);
eq("time 25",p.parseTimeFlexible("25:00"),null);
eq("time seconds",p.parseTimeFlexible("9:00:30 am"),540);
eq("role admin pm",p.parseRole("Admin, Project Manager"),{role:"ADMIN",unknown:[]});
eq("role team mgr",p.parseRole("Team Manager"),{role:"LEADER",unknown:[]});
eq("role blank",p.parseRole(""),{role:"MEMBER",unknown:[]});
eq("role our export",p.parseRole("Team/Project Manager"),{role:"LEADER",unknown:[]});
eq("role location",p.parseRole("Location manager"),{role:"LOCATION",unknown:[]});
eq("role member",p.parseRole("Team member"),{role:"MEMBER",unknown:[]});
eq("role unknown",p.parseRole("Wizard, Admin"),{role:"ADMIN",unknown:["Wizard"]});
eq("weekly 8x5",p.weeklyFromCapacity("8","Mon, Tue, Wed, Thu, Fri"),40);
eq("weekly 4x5",p.weeklyFromCapacity("4","Mon, Tue, Wed, Thu, Fri"),20);
eq("weekly none",p.weeklyFromCapacity("",""),undefined);
eq("weekly 7.5 4 days",p.weeklyFromCapacity("7:30","Monday, Tuesday, Wednesday, Thursday"),30);
eq("weekly bad",p.weeklyFromCapacity("lots","Mon"),null);
eq("weekly cap only",p.weeklyFromCapacity("8",""),40);
eq("split",p.splitList("T4, T2; t4 ,, x"),["T4","T2","x"]);
eq("refs",p.projectRefs("New Project:New Client"),[{name:"New Project:New Client"},{name:"New Project",client:"New Client"}]);
eq("pick",p.pick({a:"",b:" x "},"a","b"),"x");
// Added with the hardening pass: names, durations, access words, budgets, header spacing.
eq("clean spaces", p.clean("  Acme \n  Co\t"), "Acme Co");
eq("clean control", p.clean("A\u0000B"), "A B");
eq("dur decimal", p.parseDurationFlexible("1.5"), 90);
eq("dur h:mm", p.parseDurationFlexible("8:00"), 480);
eq("dur h:mm:ss", p.parseDurationFlexible("08:00:00"), 480);
eq("dur h:mm:ss secs", p.parseDurationFlexible("1:30:45"), 91);
eq("dur 1h 30m", p.parseDurationFlexible("1h 30m"), 90);
eq("dur 90m", p.parseDurationFlexible("90m"), 90);
eq("dur 1:75 rejected", p.parseDurationFlexible("1:75"), NaN);
eq("dur words rejected", Number.isNaN(p.parseDurationFlexible("lots")), true);
eq("dur empty rejected", Number.isNaN(p.parseDurationFlexible("")), true);
eq("dur 1e3 rejected", Number.isNaN(p.parseDurationFlexible("1e3")), true);
eq("dur Infinity rejected", Number.isNaN(p.parseDurationFlexible("Infinity")), true);
eq("access blank", p.parseAccess(""), "PUBLIC");
eq("access everyone", p.parseAccess("Everyone"), "PUBLIC");
eq("access restricted", p.parseAccess("Restricted"), "RESTRICTED");
eq("access private", p.parseAccess(" private "), "RESTRICTED");
eq("access typo", p.parseAccess("Restriced"), null);
eq("budget blank", p.parseBudget(""), null);
eq("budget zero", p.parseBudget("0"), null);
eq("budget 120", p.parseBudget("120"), 120);
eq("budget 12.5", p.parseBudget("12.5"), 12.5);
eq("budget Infinity", Number.isNaN(p.parseBudget("Infinity") as number), true);
eq("budget hex", Number.isNaN(p.parseBudget("0x10") as number), true);
eq("budget 1e999", Number.isNaN(p.parseBudget("1e999") as number), true);
eq("budget too big", Number.isNaN(p.parseBudget("100001") as number), true);
