const {chromium}=require('playwright');
const BASE='http://localhost:3000';
(async()=>{const b=await chromium.launch({executablePath:'/opt/pw-browsers/chromium'});const p=await b.newPage({viewport:{width:1200,height:1000}});
const errs=[];p.on('pageerror',e=>errs.push(e.message));p.on('console',m=>{if(m.type()==='error'&&!/fonts|ERR_CERT/.test(m.text()))errs.push(m.text())});
await p.goto(BASE+'/login');await p.waitForLoadState('networkidle');await p.fill('#email','priya@example.com');await p.fill('#password','wrong');await p.click('button:has-text("Sign in")');await p.waitForSelector('[role=alert]');await p.waitForTimeout(800);
await p.fill('#password','password123');await p.click('button:has-text("Sign in")');await p.waitForURL('**/timesheet',{timeout:90000});
await p.screenshot({path:'/tmp/claude-0/a-sheet.png',fullPage:true});
await p.click('button:has-text("Add entry with details")');await p.selectOption('#e-project',{label:'Brand refresh'});
await p.click('dialog button:has-text("Add entry")');await p.waitForSelector('dialog [role=alert]');console.log('validation:',await p.textContent('dialog [role=alert]'));
await p.selectOption('#e-phase',{index:1});await p.selectOption('#e-tag',{index:1});await p.fill('#e-desc','Logo options');await p.fill('#e-dur','1:30');
await p.click('dialog button:has-text("Add entry")');await p.waitForTimeout(2500);
await p.screenshot({path:'/tmp/claude-0/a-sheet2.png',fullPage:true});
console.log('errors',errs);await b.close()})();
